# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd55d2abb9750567b72a45d8d025a9aa7db0661ab8615f24107ba5921138f9be34a48ac5ed16d19ba6a1235d302bbbf5abedc723266429cb06bf3f6d5cb3ab27

test:
  secret_key_base: 67b69d881fd7d66794413ea07701faa0bb0afcf7fcc944143783257afefce73bb543978d2faf95f8309d5c75e811e3db281c51205332e037ede7e9365dd1fe41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
